### ISSUE TITLE
🐛 Unable to install games using epic launcher

### ISSUE THREAD

**Issue by Sn0whax** [ookangzheng/blahdns#192]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Unable to install games on epic launcher.

**To Reproduce**

1. Open epic launcher and try install anything

**Expected behavior**
Games should install

**Logs (optional)**
Logs identifying 3 sites having issues, too much personal info in them but I've identified a site I think may be causing issues.

**Server if applicable):**
Hate to suggest the below one, but it may be worth a try
eulatracking-public-service-prod.ak.epicgames.com 

- OS: [Linux, OpenWRT]
- Hosting provider (if applicable): [OpenWRT (Works if I use dif DNS provider)]

**Client (if applicable):**

- Device: [Linux, Windows]
- OS: [Windows 10]
- Client: [Dnscrypt-v2]
- Protocol: [Dnscrypt]

**Additional context**
If you unblock this address, I can try again to see if it works.

**Comment by ookangzheng** [comment]
`eulatracking-public-service-prod.ak.epicgames.com` isnt blocked

**Comment by Sn0whax** [comment]
This appears to be fixed along the way somewhere.
